In [1]:
import numpy as np
x = np.array([1,2,3,4,5,6])
ids = [1,2,3]
print(x[ids])

[2 3 4]


In [2]:
import torch
x = torch.tensor([[1,2,3],[3,5,4], [4,5,8]])
ids1 = [1,2]
ids2 = [0,2]
print(x[ids1])
print(x[ids2])
print(x[ids1]*x[ids2])
print(x[1].shape)
print(x[:,1].shape)

tensor([[3, 5, 4],
        [4, 5, 8]])
tensor([[1, 2, 3],
        [4, 5, 8]])
tensor([[ 3, 10, 12],
        [16, 25, 64]])
torch.Size([3])
torch.Size([3])
