In [1]:
import numpy as np
x = np.array([1,2,3,4,5,6])
ids = [1,2,3]
print(x[ids])

[2 3 4]


In [2]:
import torch
x = torch.tensor([[1,2,3],[3,5,4], [4,5,8]])
ids1 = [1,2]
ids2 = [0,2]
print(x[ids1])
print(x[ids2])
print(x[ids1]*x[ids2])
print(x[1].shape)
print(x[:,1].shape)

tensor([[3, 5, 4],
        [4, 5, 8]])
tensor([[1, 2, 3],
        [4, 5, 8]])
tensor([[ 3, 10, 12],
        [16, 25, 64]])
torch.Size([3])
torch.Size([3])


In [5]:
fpath = "/data2/home/zhaoyi/labs/USTC-labs/deeplearn_lab4_gcn/datasets/ppi/ppi-feats.npy"
fr = open(fpath,"r")
cnt = 10
lines = fr.readlines()
for line in lines[10]:
    print(line)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

In [14]:
import numpy as np
file = np.load('/data2/home/zhaoyi/labs/USTC-labs/deeplearn_lab4_gcn/datasets/ppi/ppi-feats.npy')
print(file[:10])
print(type(file), file.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [18]:
import json
fr = open('/data2/home/zhaoyi/labs/USTC-labs/deeplearn_lab4_gcn/datasets/ppi/ppi-G.json',"r")
mydict = json.load(fr)
print(len(mydict["links"]))
links = mydict["links"]
edges = [[links[i]["source"] for i in range(len(links))], [links[i]["target"] for i in range(len(links))]]
print(len(edges[1]))
print(mydict["nodes"][1])
fr2 = open('/data2/home/zhaoyi/labs/USTC-labs/deeplearn_lab4_gcn/datasets/ppi/ppi-class_map.json',"r")
mydict2 = json.load(fr2)
print(len(mydict2), mydict2["0"])


818716
818716
{'test': False, 'id': 1, 'val': False}
56944 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0]


In [22]:
import torch
label = torch.tensor([[1, 0, 1.], [1, 1., 1.] ])
pred = torch.tensor([[10, -20., -4.], [-1., 2., 5.]])
criterion = torch.nn.BCEWithLogitsLoss()
print(criterion(pred, label))

tensor(0.9109)


In [25]:
a = [[2,3,4],[2,3,5]]
b = [1,2,3]
import numpy as np
x = np.array(a,dtype=np.int32)
print(x)

[[2 3 4]
 [2 3 5]]
